import type { Vehicle } from "../types/vehicles.types";

export const FEATURED_VEHICLES: Vehicle[] = [
  {
    badgeText: "Certified Pre-Owned",
    colorString: "Frozen Blue Metallic · Performance Battery Plus",
    historyText: "Clean Hist.",
    id: "f-1",
    imageAlt: "Metallic Frozen Blue 2023 Porsche Taycan 4S",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB4y51NaFw6ubrlTwufIXvESgVK45wkjNz0F26Tt6opz0v_4o2FaM0EiCffyeyDUrLc6RlXxTRf6z0YoyeFPzmtrvm2hXyUt-jrW4M3wY7mrO4TkVbWlHnVuwKQoS-GC7SwLeAZbna1DirgfBeYCAFY2sGkUaeeft_5FwordFm3hj49h9BULU8sACuEXaW1bCP-xk9ANnG-bIZEE6BLrs29Ez1nXRXuzikGAqMsnWojbONjch6zmOxj",
    make: "Porsche",
    model: "Taycan",
    monthlyEstimate: "$1,240",
    price: "$89,500",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Electric",
      stat1: "8,200",
      stat2: "AWD Dual",
      stat3: "522 hp",
      stat3Color: "tertiary",
    },
    trim: "4S AWD",
    year: "2023",
  },
  {
    badgeText: "Single Owner",
    colorString: "Matterhorn White · Seville Red Nappa",
    historyText: "1-Owner",
    id: "f-2",
    imageAlt: "Matterhorn White 2024 Genesis GV70 SUV",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDr2_bITmSTcZp03iAq9rcunw2LxlANHO1VHGLbHYBgUlY8I7C0r5ZZP5eu8hQ1W8MCBC0M8Z0kPdrNA_rXBJ2cqUk8-_S_srvnI6uaeKZYauBua2NkQNp36tgyQCna2NgETpqQ1zqSyFy2iCCeEwbXOay3nG2UmIBffEHZYIsCCr6lM1U5LHCee3sMbC4MWYGQxbgEdxQvKQINNC76B5Ctzn-K98GYL4G0Qbu8_WAOMqf6Y4znDnNV",
    make: "Genesis",
    model: "GV70",
    monthlyEstimate: "$580",
    price: "$42,900",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Turbo I4",
      stat1: "11,400",
      stat2: "AWD",
      stat3: "300 hp",
    },
    trim: "2.5T Sport",
    year: "2024",
  },
  {
    badgeText: "Clean Provenance",
    colorString: "Isle of Man Green · Kyalami Orange",
    historyText: "1-Owner",
    id: "f-3",
    imageAlt: "Isle of Man Green 2023 BMW M3 Competition",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA3tAIGVTNf7ozkuQSrOImeqnpFc2u8Ug6c2Q6-T2c3Wy9nQkOULfTXmRQU23u8zJq5_bBLPxD6tXeGKyvlW65HwX16AJ3rDTUHUpeHwIymtkNwTxo_s5zZ90DhvYUfIk3rdBlZ4C5IjGBsKJQ1G8n2AyUykYH7ZA9mp_ql3N20pkFvM0PCkelsbgkh2yeVJyi5hX0TCSBykvwZX3mPxUoqfbl86jB1Zi0Ry-h8edLj1PXdzAtIdscm",
    make: "BMW",
    model: "M3",
    monthlyEstimate: "$1,090",
    price: "$78,900",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Twin Turbo",
      stat1: "6,100",
      stat2: "xDrive AWD",
      stat3: "503 hp",
    },
    trim: "Competition",
    year: "2023",
  },
  {
    badgeText: "150-Pt Inspected",
    colorString: "Caviar Black · Macadamia Semi-Aniline",
    historyText: "Certified",
    id: "f-4",
    imageAlt: "Caviar Black 2024 Lexus RX 350h Luxury hybrid SUV",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZtTMmHDXTOzpUK3j3kIwlO6ZpJ_l0pTlQvK-BuAURrPo6_i7TZYKEvp5ZAxFRb0RO8KNJJv5lPm2ChyTZtB_ayE4qswKS8VbX5pWAGWixLB3qG7-MSMALOlMqmhRybev-azrNPJB_lXNGjCK2lM2inNXIFRjBgJOZwj6ir187NjczLJam04DrWZ8ttfq4vvcimAbxSmD9LC96dLGduc94EaUAdijYbaY6h1jjrk3G7wEl9yAcpl2x",
    make: "Lexus",
    model: "RX 350h",
    monthlyEstimate: "$625",
    price: "$46,500",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Combined",
      stat1: "14,300",
      stat2: "E-Four AWD",
      stat3: "37 MPG",
      stat3Color: "tertiary",
    },
    trim: "Luxury Hybrid",
    year: "2024",
  },
];

export const EVERYDAY_VEHICLES: Vehicle[] = [
  {
    badgeText: "Family Pick",
    colorString: "Wind Chill Pearl · Black SofTex",
    historyText: "1-Owner",
    id: "e-1",
    imageAlt: "Wind Chill Pearl 2024 Toyota Highlander Hybrid",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDvFD36KWowFHdEqLqqe_8AI1yNDuUU8-nWut89ppy-Dh_oQIfQHSFxs0uPLI9G7dSZ6FS4rJdebysFwUcST_X9DmJkClnbYlSzx0T6eE1RAa2oF2yPbXueim9CqeGgB13Dcz3VSfcEGuJlo-vtRKv25n8WUqs7WpeE41dcrODCbc8zJ-KCvs3pHmCHhdkXlPysdxWjgJmjXYABL24XSdEsSk40ejBfAbAE4QSn7IzkM-MEnHrCMCKX",
    make: "Toyota",
    model: "Highlander",
    monthlyEstimate: "$540",
    price: "$42,500",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Hybrid",
      stat1: "12,000",
      stat2: "AWD",
      stat3: "36 MPG",
      stat3Color: "tertiary",
    },
    trim: "XLE Hybrid",
    year: "2024",
  },
  {
    badgeText: "Commuter Choice",
    colorString: "Meteorite Gray · Black Leather",
    historyText: "Clean Hist.",
    id: "e-2",
    imageAlt: "Meteorite Gray 2024 Honda Civic Touring",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB4y51NaFw6ubrlTwufIXvESgVK45wkjNz0F26Tt6opz0v_4o2FaM0EiCffyeyDUrLc6RlXxTRf6z0YoyeFPzmtrvm2hXyUt-jrW4M3wY7mrO4TkVbWlHnVuwKQoS-GC7SwLeAZbna1DirgfBeYCAFY2sGkUaeeft_5FwordFm3hj49h9BULU8sACuEXaW1bCP-xk9ANnG-bIZEE6BLrs29Ez1nXRXuzikGAqMsnWojbONjch6zmOxj",
    make: "Honda",
    model: "Civic",
    monthlyEstimate: "$380",
    price: "$29,900",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Engine",
      stat1: "8,500",
      stat2: "FWD",
      stat3: "1.5L Turbo",
    },
    trim: "Touring",
    year: "2024",
  },
  {
    badgeText: "Adventure Ready",
    colorString: "Polymetal Gray · Terracotta",
    historyText: "1-Owner",
    id: "e-3",
    imageAlt: "Polymetal Gray 2024 Mazda CX-50",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDr2_bITmSTcZp03iAq9rcunw2LxlANHO1VHGLbHYBgUlY8I7C0r5ZZP5eu8hQ1W8MCBC0M8Z0kPdrNA_rXBJ2cqUk8-_S_srvnI6uaeKZYauBua2NkQNp36tgyQCna2NgETpqQ1zqSyFy2iCCeEwbXOay3nG2UmIBffEHZYIsCCr6lM1U5LHCee3sMbC4MWYGQxbgEdxQvKQINNC76B5Ctzn-K98GYL4G0Qbu8_WAOMqf6Y4znDnNV",
    make: "Mazda",
    model: "CX-50",
    monthlyEstimate: "$460",
    price: "$35,800",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Engine",
      stat1: "5,200",
      stat2: "AWD",
      stat3: "2.5L Turbo",
    },
    trim: "Turbo Premium",
    year: "2024",
  },
  {
    badgeText: "Reliable Value",
    colorString: "Crystal Black Silica · Black Cloth",
    historyText: "Certified",
    id: "e-4",
    imageAlt: "Crystal Black 2024 Subaru Crosstrek",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA3tAIGVTNf7ozkuQSrOImeqnpFc2u8Ug6c2Q6-T2c3Wy9nQkOULfTXmRQU23u8zJq5_bBLPxD6tXeGKyvlW65HwX16AJ3rDTUHUpeHwIymtkNwTxo_s5zZ90DhvYUfIk3rdBlZ4C5IjGBsKJQ1G8n2AyUykYH7ZA9mp_ql3N20pkFvM0PCkelsbgkh2yeVJyi5hX0TCSBykvwZX3mPxUoqfbl86jB1Zi0Ry-h8edLj1PXdzAtIdscm",
    make: "Subaru",
    model: "Crosstrek",
    monthlyEstimate: "$340",
    price: "$26,500",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Engine",
      stat1: "9,100",
      stat2: "S-AWD",
      stat3: "2.5L Boxer",
    },
    trim: "Sport",
    year: "2024",
  },
];

export const RECENTLY_SOLD_VEHICLES: Vehicle[] = [
  {
    badgeText: "SOLD",
    colorString: "Guards Red · Black Leather",
    historyText: "1-Owner",
    id: "s-1",
    imageAlt: "Guards Red 2022 Porsche 911 GT3",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuA3tAIGVTNf7ozkuQSrOImeqnpFc2u8Ug6c2Q6-T2c3Wy9nQkOULfTXmRQU23u8zJq5_bBLPxD6tXeGKyvlW65HwX16AJ3rDTUHUpeHwIymtkNwTxo_s5zZ90DhvYUfIk3rdBlZ4C5IjGBsKJQ1G8n2AyUykYH7ZA9mp_ql3N20pkFvM0PCkelsbgkh2yeVJyi5hX0TCSBykvwZX3mPxUoqfbl86jB1Zi0Ry-h8edLj1PXdzAtIdscm",
    make: "Porsche",
    model: "911",
    monthlyEstimate: "$2,850",
    price: "$210,000",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Engine",
      stat1: "4,200",
      stat2: "RWD",
      stat3: "4.0L F6",
    },
    trim: "GT3",
    year: "2022",
  },
  {
    badgeText: "SOLD",
    colorString: "Santorini Black · Ebony Windsor",
    historyText: "Clean Hist.",
    id: "s-2",
    imageAlt: "Santorini Black 2023 Range Rover Sport",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB4y51NaFw6ubrlTwufIXvESgVK45wkjNz0F26Tt6opz0v_4o2FaM0EiCffyeyDUrLc6RlXxTRf6z0YoyeFPzmtrvm2hXyUt-jrW4M3wY7mrO4TkVbWlHnVuwKQoS-GC7SwLeAZbna1DirgfBeYCAFY2sGkUaeeft_5FwordFm3hj49h9BULU8sACuEXaW1bCP-xk9ANnG-bIZEE6BLrs29Ez1nXRXuzikGAqMsnWojbONjch6zmOxj",
    make: "Land Rover",
    model: "Range Rover Sport",
    monthlyEstimate: "$1,350",
    price: "$95,500",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Engine",
      stat1: "12,100",
      stat2: "AWD",
      stat3: "3.0L I6",
    },
    trim: "Dynamic SE",
    year: "2023",
  },
  {
    badgeText: "SOLD",
    colorString: "Rosso Corsa · Crema Leather",
    historyText: "Certified",
    id: "s-3",
    imageAlt: "Rosso Corsa 2021 Ferrari F8 Tributo",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZtTMmHDXTOzpUK3j3kIwlO6ZpJ_l0pTlQvK-BuAURrPo6_i7TZYKEvp5ZAxFRb0RO8KNJJv5lPm2ChyTZtB_ayE4qswKS8VbX5pWAGWixLB3qG7-MSMALOlMqmhRybev-azrNPJB_lXNGjCK2lM2inNXIFRjBgJOZwj6ir187NjczLJam04DrWZ8ttfq4vvcimAbxSmD9LC96dLGduc94EaUAdijYbaY6h1jjrk3G7wEl9yAcpl2x",
    make: "Ferrari",
    model: "F8 Tributo",
    monthlyEstimate: "$4,100",
    price: "$315,000",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Twin Turbo",
      stat1: "3,500",
      stat2: "RWD",
      stat3: "710 hp",
      stat3Color: "tertiary",
    },
    trim: "Base",
    year: "2021",
  },
  {
    badgeText: "SOLD",
    colorString: "Onyx Black · Obsidian Black",
    historyText: "1-Owner",
    id: "s-4",
    imageAlt: "Onyx Black 2023 Aston Martin DBX",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDr2_bITmSTcZp03iAq9rcunw2LxlANHO1VHGLbHYBgUlY8I7C0r5ZZP5eu8hQ1W8MCBC0M8Z0kPdrNA_rXBJ2cqUk8-_S_srvnI6uaeKZYauBua2NkQNp36tgyQCna2NgETpqQ1zqSyFy2iCCeEwbXOay3nG2UmIBffEHZYIsCCr6lM1U5LHCee3sMbC4MWYGQxbgEdxQvKQINNC76B5Ctzn-K98GYL4G0Qbu8_WAOMqf6Y4znDnNV",
    make: "Aston Martin",
    model: "DBX",
    monthlyEstimate: "$2,450",
    price: "$178,900",
    specs: {
      label1: "Miles",
      label2: "Drive",
      label3: "Twin Turbo",
      stat1: "8,900",
      stat2: "AWD",
      stat3: "542 hp",
    },
    trim: "V8",
    year: "2023",
  },
];
